import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import NavPanel from "@/components/header/navPanel"
import Footer from "@/components/footer/footer"

const inter = Inter({
  subsets: ["latin"],
  weight: "500",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header>
          <NavPanel />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
