import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import NavPanel from "@/components/header/navPanel"
import Footer from "@/components/footer/footer"
import TanstackProvider from "@/lib/ReactQueryProvider/ReactQuery"
export const dynamic = "force-dynamic"
export const dynamicParams = true

const inter = Inter({
  subsets: ["latin"],
  weight: "500",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <TanstackProvider>
          <header>
            <NavPanel />
          </header>
          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
        </TanstackProvider>
      </body>
    </html>
  )
}
